### ISSUE TITLE
AesBase64TomcatListenerShell的密钥问题

### ISSUE THREAD

**Issue by YYHYlh** [BeichenDream/GodzillaMemoryShellProject#3]
问题：
内存马的加解密key和哥斯拉中生成的key不一致。导致在内存马和客户端填入的key不一致的情况下无法运行。

原因：
哥斯拉在编码数据发送前，会在shells.cryptions.JavaAes.JavaAesBase64类的init方法中使用ShellEntity的getSecretKeyX方法将用户填入的key进行md5哈希
```
public String getSecretKeyX() {
    return functions.md5(this.getSecretKey()).substring(0, 16);
}
```
但是在AesBase64TomcatListenerShell的run函数的解密逻辑中，未对内存马中的key参数进行md5，而是进行aes解密。因此在实际使用中，哥斯拉客户端填写一个key，在内存马中的key需要填写成该key在经过getSecretKeyX()后的对应值才可以正常解密。不知道这个是作者的设计还是bug
```
      if (value != null) {
          byte[] data = base64Decode(value);
          data = aes(data, false);
          if (data != null && data.length > 0) {
```

**Comment by BeichenDream** [comment]
这个项目中的key是计算后的key，不是客户端生成时填写的key，是生成后的key

![image](https://github.com/BeichenDream/GodzillaMemoryShellProject/assets/43266206/2155309d-20d0-4572-a5ac-23a0852bfa59)

![image](https://github.com/BeichenDream/GodzillaMemoryShellProject/assets/43266206/358a93ac-707e-43bc-a20a-7f729eaba14b)

**Comment by YYHYlh** [comment]
谢谢师傅 明白了。这里个人感觉稍微存在点易用性上的问题，因为如果使用这个内存马项目，正常来说不需要去客户端生成webshell这个步骤。个人看法哈 说的不对师傅忽略即可
